# fly.toml app configuration file generated for music-history-core on 2024-03-26T20:57:32+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'music-history-core'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
